### ISSUE TITLE
Rozpadlý bottom bat na Androidu 4.4 (Nexus 5)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludekv/a-drake#270]
```
viz screenshot
Testováno Na Nexus 5 s Androidem 4.4.3
```

Original issue reported on code.google.com by `tomas.pr...@gmail.com` on 13 Feb 2014 at 6:26

Attachments:
- [2014-02-13 18.03.09.png](https://storage.googleapis.com/google-code-attachments/a-drake/issue-270/comment-0/2014-02-13 18.03.09.png)

**Comment by ludekv** [comment]
Řeší veze 5
