### ISSUE TITLE
Chybné zobrazení na ASUS Fonepad

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludekv/a-drake#297]
```
Na Asus Fonepad (viz 
https://www.alza.cz/asus-fonepad-me372cg-8gb-3g-gsm-sedy-d464174.htm#alternativy
 ) se nezobrazuje správně lišta menu - je překryta černým pruhem. Viz 
přiložený screenshot.
Toto se projevovalo na Android 4.4 i nyní po upgradeu na Android 5.0

```

Original issue reported on code.google.com by `tomas.pr...@gmail.com` on 4 Apr 2015 at 9:35

Attachments:
- [Screenshot_2015-04-04-11-23-28.jpg](https://storage.googleapis.com/google-code-attachments/a-drake/issue-297/comment-0/Screenshot_2015-04-04-11-23-28.jpg)

**Comment by ludekv** [comment]
Řeší verze 5
