### ISSUE TITLE
Uložené logy

### ISSUE THREAD

**Issue by Mikeant** [ludekv/a-drake#301]
Při uložení logu se do textu logu nezapíše údaj ze šablony, který se doplňuje při odeslání do FN nebo přímo jako log na GC. V exportovaném GPX pak sice je uložený log, avšak bez údaje ze šablony (v mém případě času nálezu) - tak pak dělá problémy při importu do exportovaného GPX do GG.

**Comment by ludekv** [comment]
Toto není podporovaný způsob práce. Předpokládá se export FN nebo odeslání na web a aktualizace GeoGetu pomocí LiveAPI z webu. Pak je vše korektní.
Neodeslaný log se ukládá jen jako text a neaplikuje se na něj šablona, protože např. pořadové číslo se může ještě měnit, pokud někdo loguje napřeskáčku, třeba proto, že si něco zapomněl poznamenat.

**Comment by Mikeant** [comment]
Nebylo by tedy vhodné tyto neodeslané logy vynechat při exportu do GPX? Pokud po importu takového souboru provedu aktualizaci Geogetu přes LiveAPI, moje logy se znovu nestáhnou, jelikož již u keše jsou (navíc s časem nálezu  0:00).

**Comment by Mikeant** [comment]
Ještě jedna poznámka - on se ten údaj ze šablony do textu logu nezapíše ani po odeslání do FN či jako FI logu na web. Takže pro propsání údaje ze šablony do logu uloženého v adrake je nutná zpětná aktualizace logů z webu.

**Comment by ludekv** [comment]
Propsat by se to po odeslání během přesunu z čekajících do normálních logů mohlo. To upravím.

**Comment by Mikeant** [comment]
Děkuji... hodně to pomůže
