### ISSUE TITLE
Po aktualizaci zmizí cache z mapy

### ISSUE THREAD

**Issue by majopes** [ludekv/a-drake#303]
Po aktualizaci vybrané cache přes "aktualizovat z webu" - "Celý listing" při návratu na mapu zmizí přibližně 95% normálně zobrazených cache, pomůže jen restart aplikace.

Zařízení: Honor 3C, Huawei Ascend Y300
![pred aktualizaci](https://cloud.githubusercontent.com/assets/14926083/10227128/eb5b4176-686b-11e5-8094-c6cd42f8dfaf.png)
![aktualizace](https://cloud.githubusercontent.com/assets/14926083/10227146/fcc8f39a-686b-11e5-991a-f19a72b70723.png)
![po aktualizaci](https://cloud.githubusercontent.com/assets/14926083/10227160/06c01ba8-686c-11e5-8b25-851159e00738.png)

**Comment by ludekv** [comment]
[logcat.txt](https://github.com/ludekv/a-drake/files/20303/logcat.txt)

**Comment by ludekv** [comment]
Problém se mi nepodařilo zopakovat, při testování se mi i po aktualizaci mapa vykreslila správně.

**Comment by majopes** [comment]
U nejnovější verze 5.06 se mi mapa vykreslí už taky správně. Díky
