### ISSUE TITLE
Ukládání logů pro FN

### ISSUE THREAD

**Issue by Arne1** [ludekv/a-drake#305]
I když je v Nastavení / Odeslání na web  nastaveno "Jen uložit..." tak se u každého logu snaží komunikovat s Live API - přitom Live API není v aDrake povoleno (není přihlášeno) a není ani k dispozici Internetové připojení-

**Comment by ludekv** [comment]
Jednou se mi to stalo taky, ale zdá se, že to nebyl pokus o komunikaci, ale zapomenutá nesmyslná hláška. Snad opraveno.

**Comment by Arne1** [comment]
Minulý víkend jsem něco kutil pod WiFinou a přihlásil jsem se přes aDrake na API Zeměmluvu. A i když v terénu nejsem připojenej, tak už to neotravovalo - tohle by ti snad mohlo pomoct.
