### ISSUE TITLE
Problematicky exportovany GPX

### ISSUE THREAD

**Issue by gord951** [ludekv/a-drake#309]
GPX vytvoreny exportem (filtr podle novejsich, ale stejny problem asi bude vzdy) ma nasledujici problemy:
1. obsahuje krome zmenenych kesi i kese, ktere byly jen zobrazeny
2. souradnice kese jsou presunuty na finalovy bod a je vytvoren Reference point s prefixem OL a puvodnimi vychozimi souradnicemi - GPX nemuze menit souradnice kese timto zpusobem, to je veci prezentace, muze to tak byt zobrazeno na mape, ale ne upraveno v datech
3. pokud takovy GPX importuji do GG a pak prenesu zpet do telefonu a znovu kes exportuji do GPX, ma GPX 2 waypointy s totoznym prefixem OL. Druhy uz ma ovsem stejne souradnice jako finalku (protoze souradnice kese byly presunuty na final pri predchozim exportu) a pokud GPX importuji do GG prijdu o puvodni souradnice uplne, protoze import 2. OL wp prepise ten prvni s puvodnimi souradnicemi.

**Comment by ludekv** [comment]
Export GPX při zapnutém posunu na finální souřadnice nebyl nijak speciálně ošetřený a jelikož se keš pro export načítá shodně jako pro jakékoli jiné použití, uplatnil se při tom ten posun.
Opraveno v 5.04

**Comment by Mikeant** [comment]
Co to označování pouze otevřených keší za změněné? Půjde s tím něco udělat? Chápu, že se bude muset hlídat spusta věcí (poznámka, úprava/přidání WP, atd.)
