### ISSUE TITLE
Fulltextové vyhledávání v kódu keše

### ISSUE THREAD

**Issue by Kreten8** [ludekv/a-drake#310]
Dneska se musí napsat celý GC kód od začátku aby ho to vyhledalo. Haluma udělal import turistických vizitek, kde je značí TVCZ-1023 takže když hledám vizitku, musím pokaždé napsat i to TVCZ- a je to zdlouhavé. Chtěl bych, aby stačilo napsat 1023 a ono mi jí to našlo - podobně jako to funguje v názvu.

**Comment by ludekv** [comment]
Kdy jsi to zkoušel naposledy? Tohle jsem už upravil, GC ani jiný prefix není nutný, pouze pokud text začíná GC, hledá se rychle jen podle GC kódu.

**Comment by Kreten8** [comment]
Mám verzi 5.03 a zkoušel jsem to z filtru a tam to nefunguje.
