### ISSUE TITLE
přepnutí na záložku "Kompas" (a další) resetuje polohu v Listingu

### ISSUE THREAD

**Issue by PontiacCZ** [ludekv/a-drake#311]
Rozečtený listing (tím myslím listing posunutý směrem dolů) po přepnutí na jednu ze záložek **Kompas**, **Mapa**, **Můj log**, **Logy**, **Galerie** a **Tagy** zapomene polohu. Po návratu zpět na **Listing** se tento zobrazí od prvního řádku, jako bychom na kešku přišli poprvé. Zjistil jsem to u libovolné keše.

Přepnutí na záložky **Hlavní** nebo **Waypointy** toto kupodivu nedělá.

a:Drake plus 5.04, Nexus 6, Android 5.1.1

**Comment by PontiacCZ** [comment]
U dnes aktualizované verze 5.06 sice v changelistu čtu jenom "oprava kopírování z listingu", ale zdá se (zkoušel jsem teď na dvou keškách), že jsi opravil i tento problém. Skáču na záložky Kompas, Logy, Mapa a po vrácení do listingu se dostávám zpět na původní pozici. To je skvělé a děkuju! :-)

Takže zřejmě lze uzavřít.

**Comment by ludekv** [comment]
Je to tak, ono to spolu souviselo.
