### ISSUE TITLE
informační zpráva překrývá ikony pod mapou

### ISSUE THREAD

**Issue by PontiacCZ** [ludekv/a-drake#312]
Když poprvé v detailu keše zobrazím mapu nebo přepnu na jinou vrstvu, tak poté, co se zobrazí keše, se dole zobrazí informační hláška: "Zobrazeno 2 bodů" (například). 

![screenshot_2015-10-11-16-22-56](https://cloud.githubusercontent.com/assets/9153595/10417289/6923106c-7036-11e5-9832-e318c1f26b48.png)

Tato hláška překryje některá tlačítka, jako oddálení mapy,nebo (ne)zobrazování názvů keší a waypointů. Zrovna posledně jmenované často používám a obvykle tak čekám, než hláška zmizí (i když poslední dobou jdu už po paměti).

Prosím posunout hlášku výše do prostoru mapy, tam těch pár sekund nikomu vadit nebude. :)

a:Drake plus 5.04, Nexus 6, Android 5.1.1

**Comment by ludekv** [comment]
To je standardní systémová komponenta pro hlášky, tu předělávat nebudu, nanejvýš můžu do nastavení dát možnost tu hlášku vypnout.

**Comment by PontiacCZ** [comment]
Jasně, v tom případě s tím nic nedělej. Je to celkem nepodstatná potíž a ta informace je užitečná. Pokud to do nastavení budeš chtít dát, tak tomu dej tu nejnižší prioritu, určitě máš důležitější věci. 
Můžeme uzavřít.
