### ISSUE TITLE
Sdílet souřadnice 

### ISSUE THREAD

**Issue by Mikeant** [ludekv/a-drake#316]
Nefunguje sdílení souřadnic pro novou verzi aplikace mapy.cz

**Comment by ludekv** [comment]
Asi něco změnili u Seznamu, napiš to jim :-)

**Comment by Mikeant** [comment]
Bylo by možno tedy napsat alespoň popis  způsobu, jak je sdílení souřadnic volano? Těžko jim budu vysvětlovat, že zmacknu sdílení souradnic a ono to nechodí...

**Comment by ludekv** [comment]
Používá se běžný obecný intent pro zobrazení mapy ACTION_VIEW a geo:lat,lon
https://developer.android.com/guide/components/intents-common.html#Maps

**Comment by Mikeant** [comment]
Tak jsem jim napsal , slíbili opravu v příštím týdnu. Zde možno uzavřít. Děkuji.
