### ISSUE TITLE
Ukladani logu

### ISSUE THREAD

**Issue by gord951** [ludekv/a-drake#317]
Docela me irituje nutnost ukladat napsany log samostatnym tlacitkem - pravidelne na to zapominam a musim to pak psat znovu (pokud si vsimnu, ze mi log chybi). Kdyby me alespon pri opusteni stranky upozornil, ze log neni ulozen, jestli jej nechci ulozit ...

Proc je ukladani logu reseno jinak nez treba ulozeni noveho WP, kde se automaticky WP ulozi pri opusteni stranky? Z meho pohledu jsou to dve velmi podobne akce a kazkou musim obsluhovat jinym postupem.

**Comment by PontiacCZ** [comment]
Zřejmě jsi nemyslel WP, ale něco jiného. Pro uložení WP je potřeba tapnout na "OK", jinak se neuloží. Musel jsem si to hned vyzkoušet. :)

**Comment by gord951** [comment]
Hmm, tak v tom pripade mi to OK pripada logicke, je na stejne strance, opticky k tomu patri a je to ve smeru cteni (zhora dolu) a je tam vedle jeste tlacitko Zrusit. Nenapadlo me opoustet stranku jinak nez pres OK nebo Zrusit. Kdezto u logu je tlacitko (ikonka) pro posledni krok umisten na zacatku stranky navic opticky oddelen tak, ze spis patri k nadpisu. Prinejmensim mi to v ovladani pripada nekonzistentni a navic i nelogicke. Tobe se jeste nestalo, ze jsi log neulozil a prisel o nej? Nebo to hned posilas na web? Ackoli to vim a snazim se davat na to pozor, neulozim tak jeden z 10 logu.

**Comment by PontiacCZ** [comment]
No přiznám, že nestalo, jsem na tu manuální akci zvyklý obecně z prostředí a:Drake.
Jednotlivé logy nejčastěji ukládám (jen stručné poznámky) a posléze hromadně odesílám jako Field Note.
Ale máš pravdu, že když v rozepsaném formuláři dám zpět, bez upozornění o log přijdu, toto chování potvrzuju. Taktéž prosím o úpravu.

**Comment by ludekv** [comment]
Máš pravdu, chtělo by to logy a wpt sjednotit. Zatím udělám jen drobnou úpravu, na víc není dost času. Log se při stisku tlačítka zpět automaticky uloží a do action baru přidám volbu pro zrušení (pro případ, že si editaci logu rozmyslíš).
Waypointy časem (snad) předělám v duchu logů. 
Ta nejednotnost je daná historickým vývojem.

**Comment by gord951** [comment]
Diky. Rozumim tomu, jak nejednotnost vznikla :) Mozna je volba pro zruseni zbytecna, log se da smazat uz ted (z pripravenych logu).

**Comment by ludekv** [comment]
Smazat jo, ale pokud ho začneš upravovat, nově by nebyla šance vzít to zpět. Zrušením nemyslím výmaz, ale odchod z editoru bez uložení změn

**Comment by PontiacCZ** [comment]
Ale zas nějaké storno by bylo fajn, jestli zanikne původní "storno" vrácením zpět... :)

**Comment by gord951** [comment]
Aha, tak to jsem te spatne pochopil. Pokus mas Zrusit jako Prerusit upravu (nehezky necesky = Storno), pak souhlasim.

**Comment by ludekv** [comment]
Tohle je upravené ve verzi 5.05, ale málem jsem na to zapomněl.
