### ISSUE TITLE
Na kartě posledních kešek jsou špatně vzdálenosti

### ISSUE THREAD

**Issue by Kreten8** [ludekv/a-drake#318]
Mám vybranou "kešku" TZ422 Vrchlabí a na mapě je uvedená vzdálenost 8.88 km http://geocaching.kreteni.eu/adrake/screenshot_2015-11-01-10-32-20.png , což by odpovídalo ale když se podívám na poslední kešky, tak tam jsou nesmyslné údaje 165 km http://geocaching.kreteni.eu/adrake/screenshot_2015-11-01-10-32-29.png a více u dalších z okolí

je to poslední verze 5.04

**Comment by ludekv** [comment]
Zkontroluj si nastavení referenčního bodu ve filtru.

**Comment by Kreten8** [comment]
Jo tak tím to asi bylo.
