### ISSUE TITLE
Po ťápnutí do mapy zobrazený seznam nemá škrtlé archivované kešky

### ISSUE THREAD

**Issue by Kreten8** [ludekv/a-drake#319]
Když si zobrazím seznam kešek pomocí filtru, tak archivované kešky jsou přeškrtnuté - http://geocaching.kreteni.eu/adrake/screenshot_2015-11-03-20-06-15.png
když však si nechám zobrazit seznam kešek ťápnutím do mapy, tak zde přeškrtnuté nejsou - http://geocaching.kreteni.eu/adrake/screenshot_2015-11-03-20-14-16.png

poslední verze 5.04

**Comment by ludekv** [comment]
Je to tak. neřešil jsem to, ale je lepší to sjednotit. Bude v 5.07
