### ISSUE TITLE
Neviditelné popisky zobrazených bodů

### ISSUE THREAD

**Issue by zlicinaci** [ludekv/a-drake#321]
V poslední verzi se mi stalo, že skoro nevidím názvy bodů v mapě. Mohly by být třeba černé? Nebo jinak viditelné? Děkuji. Samsung Galaxy S5.
![screenshot_2015-11-09-05-53-18](https://cloud.githubusercontent.com/assets/15739770/11042686/d81ebdba-8718-11e5-970b-f9100c05988e.png)

**Comment by PontiacCZ** [comment]
Potvrzuju toto chování i u mě na Nexus 6. A nejen poslední verze, ale vlastně co pamatuju, tak všechny verze a:Drake 5.
Už jsem uvažoval, že bude potřeba se povrtat v zobrazovacím schématu, ale až teď jsem si všiml, že stejně se zobrazuje i text v měřítku.

**Comment by ludekv** [comment]
Zkuste upravit velikost popisků v nastavení mapy.

Dne 10. listopadu 2015 7:32 PontiacCZ notifications@github.com napsal(a):

**Comment by PontiacCZ** [comment]
Já mám nastaveno popisky keší "malé" - "střední" a "velké" jsou moc velké a "automaticky", ty jsou úplně mega. :-) Nicméně ve všech případech to vypadá jako výše na obrázku - tj. písmo má jen tenkou konturu bez výplně. Přidávám své screenshoty pro obě krajní velikostní nastavení.

Automaticky:
![automaticky_50pct](https://cloud.githubusercontent.com/assets/9153595/11058839/e00fa4c6-8795-11e5-8d2b-5d3ab1dd562c.png)

Malé:
![male_50pct](https://cloud.githubusercontent.com/assets/9153595/11058838/e00b3012-8795-11e5-9bb1-a007c78eb3ec.png)

**Comment by zlicinaci** [comment]
Potvrzuji stejný stav i u mě.

**Comment by ludekv** [comment]
Opraveno ve verzi 5.05
