### ISSUE TITLE
Vyber bloku v listingu pro kopirovani

### ISSUE THREAD

**Issue by Mikeant** [ludekv/a-drake#323]
Pokud chci vybrat blok pro zkopírování v listingu (např. při kopírování vzorce) a listing je delší než obrazovka, vždy mi listing pri pokusu označení začátku nebo konce bloku odroluje na začátek, takže není možné blok označit.

**Comment by PontiacCZ** [comment]
Potvrzuju, s překvapením na to teď hledím. Nejsem tak schopen zkopírovat prachbídný vzorec, abych jej použil do finálního waypointu. :-(

**Comment by rimuln** [comment]
No nekdy mi neco podobneho dela kdyz nema v listingu obrazky. Pak odscrolovat listing dolu je temer nemozne. Resp. pomuze vypnout data.

**Comment by ludekv** [comment]
Vypadá to, že problém způsobuje snaha držet listing na místě i po načtení a zobrazení obrázku. Nějak se to tam pere. Zatím jsem nepřišel na to, jak to udělat, aby fungovalo kopírování a zároveň se po načtení obrázku listing neposunul na začátek.
Pátraní pokračuje...

**Comment by Mikeant** [comment]
Snaha udržet listing na místě? Pokud se mi teprve načítají obrázky (a že se někdy nenačtou vůbec), stává se mi při rolování listingem, že se mi neustále vrací zpět na začátek, což je hodně otravné. Nebylo by lepší tuto funkcionalitu úplně disablovat?

**Comment by gord951** [comment]
Disaoblovat kterou vlastnost bys chtel? Udrzeni listingu na miste? To znamena, ze pri kazdem vstupu do listingu (a ze u multin tam lezes porad) bude na zacatku? To uz tu bylo a bylo to opravdu otravne.

Nebo udrzet na iste po nacteni obrazku? To by mozna nebylo tak tragicke, kdyby to "chvili" poskakovalo.

Ale je pravda, ze casto se nenacitaji vsechny obrazky a neni jasny duvod.

**Comment by ludekv** [comment]
Diskutujte na gc.cz, prosím, tady se řeší konkrétní problémy.

**Comment by rimuln** [comment]
chovani S4 mini s Android 4.4.2 
Vychozi stav Listing ma obrazky nactene:
prechod listing -> hlavni -> listing - pozice zachovana
prechod listing -> WP -> listitng -pozice zachovana
prechod listing -> kompas -> listing - listing na zacatku
prechod listing -> mapa -> listing - listing na zacatku
prechod listing -> muj log -> listing - listing na zacatku
prechod listing -> logy -> listing - listing na zacatku

=> bud umysl nebo bug v pamatovani pozice jen pro nektere prechody? 
ok diskuze dale na gc.cz

**Comment by ludekv** [comment]
Rimuln - to je celkem prosté, android si drží sousední stránky v paměti, takže z hlavni a wp se listing nenačítá znova, z ostatních ano.
Jinak oprava je snad na dobré cestě.

**Comment by ludekv** [comment]
Verze 5.06 už by se měla chovat rozumně.
