### ISSUE TITLE
Oznaceni starych WP

### ISSUE THREAD

**Issue by gord951** [ludekv/a-drake#324]
Uvital bych, v seznamu WP byly oznaceny ty, ktere jsou rucne pridane (typicky vypocitane finalky) a jsou starsi nez posledni zmena lisitngu. (Pozor, neni to totez jako datum a cas aktualizace kese!) Jednoznacne me to upozorni, ze WP nemusi byt sprave, protoze od jeho vypoctu doslo v zadani ke zmene.

Zeta zmena nemusi byt pro vypocet dulezita, to je uz na me, abych si vypocet zkontroloval. Dulezite je, abych vedel, ze ten bod muze byt spatne i kdyz jsem jej mel treba schvaleny overovatkem.

**Comment by ludekv** [comment]
To v principu lze, ale a:Drake dtupdate2 v listingu nijak neřeší. Jednoduchá implementace by fungovala správně jen na datech z GeoGetu, po aktualizaci z GcLive by to už nemuselo platit. Aby bylo vše korektní, je potřeba udělat více změn, mimo jiné začít pracovat s poli dtupdate2 a hash.
Zatím odkládám...

**Comment by ludekv** [comment]
Tak jsem to dopsal, nicméně předem upozorňuji, že to není úplně 100%. Sice počítám hint podle stejného algoritmu jako Geby, ale listing se často liší, ač je pro uživatele stále stejný. Výsledek je, že hash nesedí a listin se tedy tváří jako změněný. To znamená, že varování se zobrazí častěji, než je nutné.
Realizované to je jako červený vykřičník mezi ikonou a názvem waypointu, což je trochu potíž, protože nikdo nepochopí, co to znamená.

**Comment by gord951** [comment]
Super, dekuji.

100% neni nikdy nic a radeji falesny poplach nez zbytecna cesta. Mam zkusenost, ze i GG dostava ruzny hash pri nacteni listingu z ruznych zdroju a tedy aktualizuje listing a dtupdate2. Moje udelatko se stejnou funkci jako jsi ted doplnil pak v GG casto indikuje zmeneny listing, ackoli je stejny. Asi GS generuje do kazdeho vystupu listing jinak.

Doufam, ze kdyz jsi si s tim dal tu praci, bude to i pro ostatni uzitecne.

**Comment by PontiacCZ** [comment]
Dívám se na waypointy a v těch místech se objevivší vykřičník asi bude pro mnoho uživatelů nejasný. Nicméně podstatné je, aby to bylo zapnutelné pomocí položky v nastaveních a v defaultu vypnuto. Takže kdo si to zapne, tak bude z nastavení vědět, co to bude dělat a ostatní to nijak neovlivní.

**Comment by ludekv** [comment]
Realizováno v 5.08

**Comment by gord951** [comment]
Nevim, zda oznacovani nefunguje nebo funguje jen pro finalove body. Dnes jsem delal multinu, jejiz autor predelal vsechny fyzicke stage a dal jim i novy prefix. Mel jsem tak od kazde stage v seznamu 2 vypisy (2x stage 1, 2x stage 2, ...) Rozhodnout, ktere jsou ty spravne a kam vlastne jit bylo fakt nesnadne.

Takze prosim o oznaceni starych WP i v pripade, ze nejsou finalove a dokonce ani nemaji priznak "neprepisovat". Opravdu to ma smysl.
