### ISSUE TITLE
Vypnutí detekce internetového připojení

### ISSUE THREAD

**Issue by VasaMM** [ludekv/a-drake#331]
Sice je fajn, že a:Drake detekuje, zda jsem připojen k internetu a podle toho (ne)zobrazuje jednotlivé nabídky, ale pro mě je to spíše zdržující funkce. A to hned ze dvou důvodů:
- Nemožnost využít nabídku _Otevřít na webu_ - což díky rozpoznávání odkazů může taktéž znamenat jen otevření v jiné offline aplikaci (c:geo, Locus, ale třeba i a:Drake ve verzi pro). Využíval jsem to při testování pětkové verze a když něco nefungovalo, tak jsem se přepínal to staré 4.22 verze. Bohužel to znamenalo pokaždé zapnout internet...
- Neřeší to, zda jsem internet zapnul až po otevření detailu keše. Většinou mám při lovu vypnutý datový modul (skrze úsporu baterky) a zapínám ho, jen když je potřeba. a:Drake i proto nenabízí nabídku _Aktualizovat z webu_ a musím tak opustit keš a opět se do ní vrátit...

**Comment by ludekv** [comment]
Otevřít na webu tam můžu nechat, to celkem ničemu nevadí.
