### ISSUE TITLE
Možnost sdílet keš

### ISSUE THREAD

**Issue by VasaMM** [ludekv/a-drake#332]
Ještě mě napadlo, že by bylo fajn přidat do menu i možnost sdílet keš. Tedy něco, jak má c:geo. Tuto možnost odchytí mnohem více aplikací (třeba mail, bluetooth), takže ideální možnost pokud chci někomu poslat odkaz na keš.

**Comment by ludekv** [comment]
c:geo nepoužívám, takže, prosím, upřesni, jak si to představuješ.

**Comment by VasaMM** [comment]
No, předpokládám, že se jedná o nějaké systémové volání na sdílení textu. Tuto možnost má spousta aplikací. V případě c:gea se sdílí akorát odkaz ve formátu http://coord.info/GCXXXXX.

Tedy by to mělo fungovat podobně jako možnost _otevřít na webu_, akorát s tím rozdílem, že by se nenabídli jen internetové prohlížeče, ale všechny aplikace schopné zpracovat text (SMS klient, email, poznámky, bluetooth, apod.)

Stačí to takto?

**Comment by ludekv** [comment]
OK, dobrý námět a přitom celkem maličkost.
