### ISSUE TITLE
Aplikace spadne při startu

### ISSUE THREAD

**Issue by AtomistaCZ** [ludekv/a-drake#336]
Po upgradu na poslední verzi mi spadne aplikace hned při startu. Objeví se pouze bílá obrazovka s modrou lištou a ikonou nahoře a se zprávou aDrake Plus se zastavila. S aplikací se nedá nijak pracovat. Předchozí verze fungovaly.

Použitý přístroj:
Samsung galaxy xCover2 GT-7710

Log:
samsung
build.model: GT-S7710
build.product: skomerxx
build.radio: unknown
build.tags: release-keys
build.type: user
build.user: dpi
version.codename: REL
version.incremental: S7710XXAMB6
version.release: 4.1.2
version.sdk_int: 16

04-10 10:35:55.283 E/AndroidRuntime(24532):     at cz.adrake.MainGridFragment$ImageAdapter.getView(MainGridFragment.java:184)
04-10 10:36:02.021 E/ActivityManager(2033): App already has crash dialog: ProcessRecord{42791480 24532:cz.adrake.plus/u0a36}
04-10 10:36:03.973 I/ActivityManager(2033): Process cz.adrake.plus (pid 24532) has died.

**Comment by AtomistaCZ** [comment]
Doplňující info:
Soubor aDrake.ini měl po upgradu nulovou velikost. Obnovil jsem jej ze zálohy, ale aplikace stále nefunguje.

**Comment by PontiacCZ** [comment]
Potvrzuju padání při pokusu otevřít libovolnou cache.

A:Drake 5.09, Nexus 6, Android 6.0.1

**Comment by ludekv** [comment]
a:Drake - podařilo se vyrobit vadnou instalačku
a:Drake Plus - zavlečena blbá chyba
Obojí opraveno.
Mimochodem, adrake.ini je exportovaný soubor pro ADrakeSync v GeoGetu, takže na jeho obsahu a existenci nezáleží.

**Comment by rimuln** [comment]
Hmm.
ted jsem nainstaloval 5.10 a dela to aDrake.plus. Poslana zpetna vazba.
S4 mini A 4.4.2 
databaze a konfigurace na phone. osm mapy z paws na ext. card
