### ISSUE TITLE
komentář k waypointu se z GC.live načte do Poznámky místo do CMT

### ISSUE THREAD

**Issue by PontiacCZ** [ludekv/a-drake#340]
**Postup reprodukce:**

1) do boxu rychlého vyhledávání vpravo nahoře na hlavní obrazovce a:Drake zadej GC66KVT
2) jestliže ji nemáš v db (což asi ne, protože je to Kroměřížská novinka), načte se z GC.Live
3) otevři nově staženou cache, jdi na záložku "Waypointy" a edituj wpt "Final location".
4) ownerův komentář k waypointu se neumístil na záložku "CMT", jak by správně měl, ale do záložky  "POZNÁMKA".

**Comment by ludekv** [comment]
Tahle chyba je tam od začátku, opraveno. Dík za upozornění.
