### ISSUE TITLE
vygenerovane FN nejsou videt pres MTP

### ISSUE THREAD

**Issue by geby** [ludekv/a-drake#341]
Vygeneruji a ulozim si FN soubor, ale pres MTP soubor bud nevidim, nebo vidim predchozi verzi.

MTP driver se o zmene souboru asi nedozvi, a tak neprovede refresh filesystemu, a misto toho podstrkava do USB predchozi verzi.

Mozna by pomohlo toto:

This code seems to be able to make my new files appear over MTP, but this only seems to be working on individual files.  I tried passing in a reference to a parent directory and it didn't do anything.

```
public void makeFileDiscoverable(File file, Context context){
    MediaScannerConnection.scanFile(context, new String[]{file.getPath()}, null, null);
    context.sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE,
            Uri.fromFile(file)));
}
```

viz. [https://code.google.com/p/android/issues/detail?id=38282#c59](url)

**Comment by ludekv** [comment]
Pomůže to, dík za tip.
