### ISSUE TITLE
Pri spatnem spojeni a odesilani logu vznikaji double foundy

### ISSUE THREAD

**Issue by J4cker14** [ludekv/a-drake#344]
Neni osetreno a overovano, zda log stejneho typu (popr obsahu) je jiz odeslan u prislusne kesky. Stalo se mi ze nekolik kesek hromadne loguji a  u nektere mi to spadlo z duvodu nestabilniho slabeho pripojeni (edge). Pote jsem prisel na wifi a dal jsem odeslat znovu (zbytek seznamu) ovsem jedna z nich byla odeslana opet i kdyz se to povedlo jeste na nestabilnim pripojeni odeslat.

**Comment by ludekv** [comment]
Odeslání logu se ověřuje, nicméně pokud spojení spadne během odesílání, může se stát, že log se odeslal a uložil, ale potvrzení nepřišlo.
Asi by šlo před odesláním stáhnout logy a hledat, zda tam není stejný, ale bylo by to komplikované a zřejmě dost výrazně by to zpomalovalo odesílání.

**Comment by J4cker14** [comment]
Nyni se mi dokonce stalo ze vlozil nejen dvojnasobny log, ale ten druhy mel dvojnasobny obsah tedy:

PRVNI LOG:

#prvni poradove cislo kesky

#text

pad pri odesilani, stisknu znovu odeslat vse

bohuzel zustal log v tabulce, i kdyz byl jiz odeslan a vypadal nasledovne:

#prvni poradove cislo kesky
#prvni poradove cislo kesky

#text
#text

**Comment by Witriol** [comment]
Mám stejný problém jako J4cker14. Stává se to hlavně při odesílání logů když mám slabý mobilní signál. K logu se připojí číslo/čas/podpis a uloží se tak mezi čekající logy, takže při následném odeslání na již bezproblémovém internetovém připojení se znovu připojí číslo/čas/podpis.
