### ISSUE TITLE
Feature | Kam se podela moznost importu tras?

### ISSUE THREAD

**Issue by J4cker14** [ludekv/a-drake#345]
Byl jsem zvykly zejmena u starsi verze, importnout si gpxko a pote jit po teto trase. Nyni tuto moznost nemohu dohledat. Dlouho byla jen v plus verzi, ale nez jsem se odhodlal k jeji porizeni, tak ji tu nemuzu nalezt. Dobre by bylo importovat i vicenasobny track gpx, tedy soubor, ktery obsahuje napriklad pet tras. S vyhodou jsem toho pouzival na rally, kdy jsem si pridal RZ a kolem nich jsem hledal pripadne kesulky :-)

**Comment by ludekv** [comment]
Import tras v a:Drake nikdy nebyl a ani není v plánu. Něco takového v primitivní podobě bylo v PocketDrake pro Windows Mobile.

**Comment by J4cker14** [comment]
Myslim ze je dost lidi, co by tuto funkci klidne v te nejprimitivnejsi verzi uvotalo. Staci tak, jak jsouusle trasy v db, pouze nacist a zobrazit fixne v pame, nic vic, jenom nastavit treba barvu  a tloustku cary mozna by se hodilo jeste
