### ISSUE TITLE
a:Drake neuloží tag FTF = FTF (a jiné se shodou názvu a hodnoty)

### ISSUE THREAD

**Issue by PontiacCZ** [ludekv/a-drake#355]
Vyzkoušeno teď na dvou keších a je to, zdá se, na keši nezávislé: když zapíšu tag kategorie FTF s hodnotou FTF, v seznamu se ihned objeví. Vypnu a:Drake, znovu ho spustím, otevřu  znovu na tuto keš a tag FTF chybí. Není pouze schovaný, on prostě nebyl zapsán, což dokáže i přenos pomocí aDrakeSync do Geogetu - tag FTF = FTF se nepřenese.

Tagy FTF = STF a FTF = TTF se ukládají bez problémů.

Zkusil jsem uložit nesmyslný tag "aaa" = "aaa", který se opět neuložil, zatímco s hodnotou "aab" se uložil. 

Tedy závěr: **aDrake z neznámého důvodu nezapíše tag, jenž má hodnotu shodnou s názvem kategorie tagu.**

**Comment by ludekv** [comment]
Dík za informaci. Důvod je celkem prostý - podařilo se mi smíchat buffer pro katerogrie a hodnoty tagů, takže se ukládal nesmysl. Bude opraveno v příští verzi.
