### ISSUE TITLE
Android 7 a dialogy u logovani vedou ke crashi

### ISSUE THREAD

**Issue by J4cker14** [ludekv/a-drake#357]
Dialogy po kliknuti ma datum a cas se nezobrazi, misto toho appka crashne.

Lze nasimulovat vzdy.

Android 7, Xperia Z5c

**Comment by ludekv** [comment]
V Androidu je jistá nekompatibilita u těchto dialogů, proto to padá. Podařilo se to opravit, potíž je, že nejsem schopný říct, kdy dokážu opravu uvolnit.

**Comment by ludekv** [comment]
V 5.13 by to mělo fungovat
