### ISSUE TITLE
Propojeni s GC pres API (updated)

### ISSUE THREAD

**Issue by J4cker14** [ludekv/a-drake#360]
Mala poznamka, mam pocit, ze pri kontaktovani serveru Geocaching, dale GC, pres API dotaz, kdy je pozadovano navraceni zakladnich informaci, je vyuzit dotaz, ktery pozaduje navraceni kompletnich informaci. V tom pripade se z limitu 10000 dotazu, dostavame do skupiny se tremi dotazy za den, pri non-premium member.

Muzete prosim komentovat, nebo prezkoumat?

Dekuji

**Comment by ludekv** [comment]
Ne, stahují se omezené informace, ale změnily se limity a už to není 10k ale jen 6k.

**Comment by J4cker14** [comment]
Mrknete na video, obe dve sekce mi stahly full udaje dle informaci o prihalsnei - https://youtu.be/uJ0Tw6z5B8c

**Comment by rimuln** [comment]
a neexpiroval ti token v aDrake pro premium account? Takto se mi to chova, prave pri te expiraci. Pak je nutne se opet prihlasit a uz je vse OK.

**Comment by ludekv** [comment]
Lituju, jako BM máš ze strany Groundspeaku spoustu omezení. Investuj do PM, nic jiného s tím neudělám.

**Comment by J4cker14** [comment]
Tedy oni zrusili podporu free requestu na zakladni udaje?

**Comment by J4cker14** [comment]
V GeoGetu to funguje spravne, tedy 10tisic dotazu na kesky, v adrake jsou limity a pristupy chybne, jsem si jist, ze to v minulosti fungovalo spravne.

Import -> Stahnout kesky -> Jen zakladni udaje (souradnice, teren, velikost, druh, ...)

**Comment by Nemo02** [comment]
Souhrny nejsou to samé co Jen základní údaje.
Pokud se nepletu mají souhrny a full listing společný limit. http://www.geocaching.cz/topic/30442-gg-a-basic-member/?p=517729
