### ISSUE TITLE
Vylepse - waypointy - zobrazit final k nenalezenym

### ISSUE THREAD

**Issue by J4cker14** [ludekv/a-drake#361]
Navrh, co by se mi libilo a hodilo.

Pridat dalsi moznost nastaveni waypointu - zobrazit pouze final pro nenalezene

**Comment by ludekv** [comment]
To přece jde nastavit odedávna - zobrazovat wpt jen k nenalezeným tam je a omezení typu wpt taky.

**Comment by J4cker14** [comment]
Naprosta parada, dekuji za nakopnuti :-)
