### ISSUE TITLE
Kontrolni soucet indicii

### ISSUE THREAD

**Issue by gord951** [ludekv/a-drake#367]
Pri vypoctu vzorce se automaticky vypocita ciferny soucet ze souradnic. Obcas by se hodil i kontrolni soucet z hodnot indicii.

**Comment by PontiacCZ** [comment]
Na tom něco je. Už jsem mockrát narazil na kontrolní součet všech indicií, ale na součet všech cifer ze souřadnic zatím ne.

**Comment by gord951** [comment]
I kontrolni soucet cifer souradnic je docela bezna kontrola. Asi proto uz v aD je.

Byl jsem na multine s 24 indiciemi a byla tam kontola na soucet po prvni polovine indicii, aby se clovek nemusl vracet 20 km, ale jen 10 :-) Tak by se mozna hodilo, kdyby ten kontrolni soucet indicii bylo mozne pocitat kdykoli, i kdyz nebudou jeste zname vsechny indicie.

**Comment by ludekv** [comment]
To je dobré, sám jsem si to už nepamatoval, ale a:Drake to číslo počítá, akorát se výsledek nikde nezobrazuje. Tak ho zobrazím.

**Comment by PontiacCZ** [comment]
Nevím, nakolik to tady Luděk ještě používá (raději používám vlákno na geocaching.cz), ale tohle je zapracováno v poslední verzi 5.15.7, bylo to psáno v release notes a teď jsem si to u jedné multiny ověřil.
