### ISSUE TITLE
zleva useknutá část listingu u keše Jarošovský pivovar

### ISSUE THREAD

**Issue by PontiacCZ** [ludekv/a-drake#370]
**Keš**: Jarošovský pivovar https://coord.info/GC6XFA7

Od části s etiketama je listing zleva useknutý - viz screenshot.

![obrazek](https://user-images.githubusercontent.com/9153595/32415346-df2a49b4-c238-11e7-9c64-38df6533799d.png)

**Comment by ludekv** [comment]
HTML kód té keše je docela fuj, ve Firefoxu je to uskočené na opačnou stranu, v GeoGetu je to celé rozsypané. Pokud to chceš řešit, napiš autorovi, ať si to srovná. Já to řešit nebudu.
