### ISSUE TITLE
live vyhledavani zobrazi jen 1 kes

### ISSUE THREAD

**Issue by dbenesj** [ludekv/a-drake#371]
Pri pokusu o vyhledani kesi online je jako vysledek zobrazena jen 1 kes. Pritom podle hlasky ve spodni casti obrazovky to vypada, ze se jich stahlo 15 (na obrazku 45, protoze jsem hledani provedl jiz potreti).

Ve filtru mam nastaveno jen: nenalezene + stred mapy. V okoli je realne spousta nenalezenych.

Projevuje se po update z a:Drake Plus 5.14 na 5.15.7
Android 6.0.1
Samsung A3
![screenshot_2017-12-30-13-58-55](https://user-images.githubusercontent.com/6650648/34454382-ac09b620-ed6a-11e7-954d-159b3be8946b.png)

**Comment by ludekv** [comment]
Nalezeno a opraveno ve verzi 5.15.9
