### ISSUE TITLE
Změněný WP se neoznačí jako nepřepisovatelný

### ISSUE THREAD

**Issue by Mikeant** [ludekv/a-drake#373]
Když změním starý waypoint (např. nulovou finálku založenou ownerem), tak se nezaškrtne "Nepřepisovat při importu", tj. flag zůstane 1. V podstatě se mi flag nastaví na 0 (nepřepisovat) pouze u založení nového WP. Nevím zda to tak není schválně, ale čekal bych, že když změním souřadnice nějakého WP, označí se jako nepřepisovatelný při importu....

**Comment by ludekv** [comment]
To je vlastnost, nastavit to musíš sám. Nemám rád programy, co vnucují uživateli svoje nápady.
